[package]
name = "naive-client"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
solana-sdk = "1.17"
solana-rpc-client = "1.17"
solana-logger = "1.17"
workshop-program = { workspace = true, features = ["no-entrypoint"] }
